package com.example.stefanie.countrycode;

import java.util.ArrayList;
import java.util.List;

public class CountryData {
	private static List<Country> data;

	public static List<Country> getCountryList() {
		if (data == null) {
			data = new ArrayList<Country>();
			fillList(data);
		}
		return data;
	}

	private static void fillList(List<Country> data) {
		if (data != null) {
			data.add(new Country("AF", "AFGHANISTAN", "Afghanistan", "AFG", "004"));
			data.add(new Country("AL", "ALBANIA", "Albania", "ALB", "008"));
			data.add(new Country("DZ", "ALGERIA", "Algeria", "DZA", "012"));
			data.add(new Country("AS", "AMERICAN SAMOA", "American Samoa", "ASM", "016"));
			data.add(new Country("AD", "ANDORRA", "Andorra", "AND", "020"));
			data.add(new Country("AO", "ANGOLA", "Angola", "AGO", "024"));
			data.add(new Country("AI", "ANGUILLA", "Anguilla", "AIA", "660"));
			data.add(new Country("AQ", "ANTARCTICA", "Antarctica", null, null));
			data.add(new Country("AG", "ANTIGUA AND BARBUDA", "Antigua and Barbuda", "ATG", "028"));
			data.add(new Country("AR", "ARGENTINA", "Argentina", "ARG", "032"));
			data.add(new Country("AM", "ARMENIA", "Armenia", "ARM", "051"));
			data.add(new Country("AW", "ARUBA", "Aruba", "ABW", "533"));
			data.add(new Country("AU", "AUSTRALIA", "Australia", "AUS", "036"));
			data.add(new Country("AT", "AUSTRIA", "Austria", "AUT", "040"));
			data.add(new Country("AZ", "AZERBAIJAN", "Azerbaijan", "AZE", "031"));
			data.add(new Country("BS", "BAHAMAS", "Bahamas", "BHS", "044"));
			data.add(new Country("BH", "BAHRAIN", "Bahrain", "BHR", "048"));
			data.add(new Country("BD", "BANGLADESH", "Bangladesh", "BGD", "050"));
			data.add(new Country("BB", "BARBADOS", "Barbados", "BRB", "052"));
			data.add(new Country("BY", "BELARUS", "Belarus", "BLR", "112"));
			data.add(new Country("BE", "BELGIUM", "Belgium", "BEL", "056"));
			data.add(new Country("BZ", "BELIZE", "Belize", "BLZ", "084"));
			data.add(new Country("BJ", "BENIN", "Benin", "BEN", "204"));
			data.add(new Country("BM", "BERMUDA", "Bermuda", "BMU", "060"));
			data.add(new Country("BT", "BHUTAN", "Bhutan", "BTN", "064"));
			data.add(new Country("BO", "BOLIVIA", "Bolivia", "BOL", "068"));
			data.add(new Country("BA", "BOSNIA AND HERZEGOVINA", "Bosnia and Herzegovina", "BIH", "070"));
			data.add(new Country("BW", "BOTSWANA", "Botswana", "BWA", "072"));
			data.add(new Country("BV", "BOUVET ISLAND", "Bouvet Island", null, null));
			data.add(new Country("BR", "BRAZIL", "Brazil", "BRA", "076"));
			data.add(new Country("IO", "BRITISH INDIAN OCEAN TERRITORY", "British Indian Ocean Territory", null, null));
			data.add(new Country("BN", "BRUNEI DARUSSALAM", "Brunei Darussalam", "BRN", "096"));
			data.add(new Country("BG", "BULGARIA", "Bulgaria", "BGR", "100"));
			data.add(new Country("BF", "BURKINA FASO", "Burkina Faso", "BFA", "854"));
			data.add(new Country("BI", "BURUNDI", "Burundi", "BDI", "108"));
			data.add(new Country("KH", "CAMBODIA", "Cambodia", "KHM", "116"));
			data.add(new Country("CM", "CAMEROON", "Cameroon", "CMR", "120"));
			data.add(new Country("CA", "CANADA", "Canada", "CAN", "124"));
			data.add(new Country("CV", "CAPE VERDE", "Cape Verde", "CPV", "132"));
			data.add(new Country("KY", "CAYMAN ISLANDS", "Cayman Islands", "CYM", "136"));
			data.add(new Country("CF", "CENTRAL AFRICAN REPUBLIC", "Central African Republic", "CAF", "140"));
			data.add(new Country("TD", "CHAD", "Chad", "TCD", "148"));
			data.add(new Country("CL", "CHILE", "Chile", "CHL", "152"));
			data.add(new Country("CN", "CHINA", "China", "CHN", "156"));
			data.add(new Country("CX", "CHRISTMAS ISLAND", "Christmas Island", null, null));
			data.add(new Country("CC", "COCOS (KEELING) ISLANDS", "Cocos (Keeling) Islands", null, null));
			data.add(new Country("CO", "COLOMBIA", "Colombia", "COL", "170"));
			data.add(new Country("KM", "COMOROS", "Comoros", "COM", "174"));
			data.add(new Country("CG", "CONGO", "Congo", "COG", "178"));
			data.add(new Country("CD", "CONGO, THE DEMOCRATIC REPUBLIC OF THE",
					"Congo, the Democratic Republic of the", "COD", "180"));
			data.add(new Country("CK", "COOK ISLANDS", "Cook Islands", "COK", "184"));
			data.add(new Country("CR", "COSTA RICA", "Costa Rica", "CRI", "188"));
			data.add(new Country("CI", "COTE D\"IVOIRE", "Cote D\"Ivoire", "CIV", "384"));
			data.add(new Country("HR", "CROATIA", "Croatia", "HRV", "191"));
			data.add(new Country("CU", "CUBA", "Cuba", "CUB", "192"));
			data.add(new Country("CY", "CYPRUS", "Cyprus", "CYP", "196"));
			data.add(new Country("CZ", "CZECH REPUBLIC", "Czech Republic", "CZE", "203"));
			data.add(new Country("DK", "DENMARK", "Denmark", "DNK", "208"));
			data.add(new Country("DJ", "DJIBOUTI", "Djibouti", "DJI", "262"));
			data.add(new Country("DM", "DOMINICA", "Dominica", "DMA", "212"));
			data.add(new Country("DO", "DOMINICAN REPUBLIC", "Dominican Republic", "DOM", "214"));
			data.add(new Country("EC", "ECUADOR", "Ecuador", "ECU", "218"));
			data.add(new Country("EG", "EGYPT", "Egypt", "EGY", "818"));
			data.add(new Country("SV", "EL SALVADOR", "El Salvador", "SLV", "222"));
			data.add(new Country("GQ", "EQUATORIAL GUINEA", "Equatorial Guinea", "GNQ", "226"));
			data.add(new Country("ER", "ERITREA", "Eritrea", "ERI", "232"));
			data.add(new Country("EE", "ESTONIA", "Estonia", "EST", "233"));
			data.add(new Country("ET", "ETHIOPIA", "Ethiopia", "ETH", "231"));
			data.add(new Country("FK", "FALKLAND ISLANDS (MALVINAS)", "Falkland Islands (Malvinas)", "FLK", "238"));
			data.add(new Country("FO", "FAROE ISLANDS", "Faroe Islands", "FRO", "234"));
			data.add(new Country("FJ", "FIJI", "Fiji", "FJI", "242"));
			data.add(new Country("FI", "FINLAND", "Finland", "FIN", "246"));
			data.add(new Country("FR", "FRANCE", "France", "FRA", "250"));
			data.add(new Country("GF", "FRENCH GUIANA", "French Guiana", "GUF", "254"));
			data.add(new Country("PF", "FRENCH POLYNESIA", "French Polynesia", "PYF", "258"));
			data.add(new Country("TF", "FRENCH SOUTHERN TERRITORIES", "French Southern Territories", null, null));
			data.add(new Country("GA", "GABON", "Gabon", "GAB", "266"));
			data.add(new Country("GM", "GAMBIA", "Gambia", "GMB", "270"));
			data.add(new Country("GE", "GEORGIA", "Georgia", "GEO", "268"));
			data.add(new Country("DE", "GERMANY", "Germany", "DEU", "276"));
			data.add(new Country("GH", "GHANA", "Ghana", "GHA", "288"));
			data.add(new Country("GI", "GIBRALTAR", "Gibraltar", "GIB", "292"));
			data.add(new Country("GR", "GREECE", "Greece", "GRC", "300"));
			data.add(new Country("GL", "GREENLAND", "Greenland", "GRL", "304"));
			data.add(new Country("GD", "GRENADA", "Grenada", "GRD", "308"));
			data.add(new Country("GP", "GUADELOUPE", "Guadeloupe", "GLP", "312"));
			data.add(new Country("GU", "GUAM", "Guam", "GUM", "316"));
			data.add(new Country("GT", "GUATEMALA", "Guatemala", "GTM", "320"));
			data.add(new Country("GN", "GUINEA", "Guinea", "GIN", "324"));
			data.add(new Country("GW", "GUINEA-BISSAU", "Guinea-Bissau", "GNB", "624"));
			data.add(new Country("GY", "GUYANA", "Guyana", "GUY", "328"));
			data.add(new Country("HT", "HAITI", "Haiti", "HTI", "332"));
			data.add(new Country("HM", "HEARD ISLAND AND MCDONALD ISLANDS", "Heard Island and Mcdonald Islands", null,
					null));
			data.add(new Country("VA", "HOLY SEE (VATICAN CITY STATE)", "Holy See (Vatican City State)", "VAT", "336"));
			data.add(new Country("HN", "HONDURAS", "Honduras", "HND", "340"));
			data.add(new Country("HK", "HONG KONG", "Hong Kong", "HKG", "344"));
			data.add(new Country("HU", "HUNGARY", "Hungary", "HUN", "348"));
			data.add(new Country("IS", "ICELAND", "Iceland", "ISL", "352"));
			data.add(new Country("IN", "INDIA", "India", "IND", "356"));
			data.add(new Country("ID", "INDONESIA", "Indonesia", "IDN", "360"));
			data.add(new Country("IR", "IRAN, ISLAMIC REPUBLIC OF", "Iran, Islamic Republic of", "IRN", "364"));
			data.add(new Country("IQ", "IRAQ", "Iraq", "IRQ", "368"));
			data.add(new Country("IE", "IRELAND", "Ireland", "IRL", "372"));
			data.add(new Country("IL", "ISRAEL", "Israel", "ISR", "376"));
			data.add(new Country("IT", "ITALY", "Italy", "ITA", "380"));
			data.add(new Country("JM", "JAMAICA", "Jamaica", "JAM", "388"));
			data.add(new Country("JP", "JAPAN", "Japan", "JPN", "392"));
			data.add(new Country("JO", "JORDAN", "Jordan", "JOR", "400"));
			data.add(new Country("KZ", "KAZAKHSTAN", "Kazakhstan", "KAZ", "398"));
			data.add(new Country("KE", "KENYA", "Kenya", "KEN", "404"));
			data.add(new Country("KI", "KIRIBATI", "Kiribati", "KIR", "296"));
			data.add(new Country("KP", "KOREA, DEMOCRATIC PEOPLE\"S REPUBLIC OF",
					"Korea, Democratic People\"s Republic of", "PRK", "408"));
			data.add(new Country("KR", "KOREA, REPUBLIC OF", "Korea, Republic of", "KOR", "410"));
			data.add(new Country("KW", "KUWAIT", "Kuwait", "KWT", "414"));
			data.add(new Country("KG", "KYRGYZSTAN", "Kyrgyzstan", "KGZ", "417"));
			data.add(new Country("LA", "LAO PEOPLE\"S DEMOCRATIC REPUBLIC", "Lao People\"s Democratic Republic", "LAO",
					"418"));
			data.add(new Country("LV", "LATVIA", "Latvia", "LVA", "428"));
			data.add(new Country("LB", "LEBANON", "Lebanon", "LBN", "422"));
			data.add(new Country("LS", "LESOTHO", "Lesotho", "LSO", "426"));
			data.add(new Country("LR", "LIBERIA", "Liberia", "LBR", "430"));
			data.add(new Country("LY", "LIBYAN ARAB JAMAHIRIYA", "Libyan Arab Jamahiriya", "LBY", "434"));
			data.add(new Country("LI", "LIECHTENSTEIN", "Liechtenstein", "LIE", "438"));
			data.add(new Country("LT", "LITHUANIA", "Lithuania", "LTU", "440"));
			data.add(new Country("LU", "LUXEMBOURG", "Luxembourg", "LUX", "442"));
			data.add(new Country("MO", "MACAO", "Macao", "MAC", "446"));
			data.add(new Country("MK", "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
					"Macedonia, the Former Yugoslav Republic of", "MKD", "807"));
			data.add(new Country("MG", "MADAGASCAR", "Madagascar", "MDG", "450"));
			data.add(new Country("MW", "MALAWI", "Malawi", "MWI", "454"));
			data.add(new Country("MY", "MALAYSIA", "Malaysia", "MYS", "458"));
			data.add(new Country("MV", "MALDIVES", "Maldives", "MDV", "462"));
			data.add(new Country("ML", "MALI", "Mali", "MLI", "466"));
			data.add(new Country("MT", "MALTA", "Malta", "MLT", "470"));
			data.add(new Country("MH", "MARSHALL ISLANDS", "Marshall Islands", "MHL", "584"));
			data.add(new Country("MQ", "MARTINIQUE", "Martinique", "MTQ", "474"));
			data.add(new Country("MR", "MAURITANIA", "Mauritania", "MRT", "478"));
			data.add(new Country("MU", "MAURITIUS", "Mauritius", "MUS", "480"));
			data.add(new Country("YT", "MAYOTTE", "Mayotte", null, null));
			data.add(new Country("MX", "MEXICO", "Mexico", "MEX", "484"));
			data.add(new Country("FM", "MICRONESIA, FEDERATED STATES OF", "Micronesia, Federated States of", "FSM",
					"583"));
			data.add(new Country("MD", "MOLDOVA, REPUBLIC OF", "Moldova, Republic of", "MDA", "498"));
			data.add(new Country("MC", "MONACO", "Monaco", "MCO", "492"));
			data.add(new Country("MN", "MONGOLIA", "Mongolia", "MNG", "496"));
			data.add(new Country("MS", "MONTSERRAT", "Montserrat", "MSR", "500"));
			data.add(new Country("MA", "MOROCCO", "Morocco", "MAR", "504"));
			data.add(new Country("MZ", "MOZAMBIQUE", "Mozambique", "MOZ", "508"));
			data.add(new Country("MM", "MYANMAR", "Myanmar", "MMR", "104"));
			data.add(new Country("NA", "NAMIBIA", "Namibia", "NAM", "516"));
			data.add(new Country("NR", "NAURU", "Nauru", "NRU", "520"));
			data.add(new Country("NP", "NEPAL", "Nepal", "NPL", "524"));
			data.add(new Country("NL", "NETHERLANDS", "Netherlands", "NLD", "528"));
			data.add(new Country("AN", "NETHERLANDS ANTILLES", "Netherlands Antilles", "ANT", "530"));
			data.add(new Country("NC", "NEW CALEDONIA", "New Caledonia", "NCL", "540"));
			data.add(new Country("NZ", "NEW ZEALAND", "New Zealand", "NZL", "554"));
			data.add(new Country("NI", "NICARAGUA", "Nicaragua", "NIC", "558"));
			data.add(new Country("NE", "NIGER", "Niger", "NER", "562"));
			data.add(new Country("NG", "NIGERIA", "Nigeria", "NGA", "566"));
			data.add(new Country("NU", "NIUE", "Niue", "NIU", "570"));
			data.add(new Country("NF", "NORFOLK ISLAND", "Norfolk Island", "NFK", "574"));
			data.add(new Country("MP", "NORTHERN MARIANA ISLANDS", "Northern Mariana Islands", "MNP", "580"));
			data.add(new Country("NO", "NORWAY", "Norway", "NOR", "578"));
			data.add(new Country("OM", "OMAN", "Oman", "OMN", "512"));
			data.add(new Country("PK", "PAKISTAN", "Pakistan", "PAK", "586"));
			data.add(new Country("PW", "PALAU", "Palau", "PLW", "585"));
			data.add(new Country("PS", "PALESTINIAN TERRITORY, OCCUPIED", "Palestinian Territory, Occupied", null, null));
			data.add(new Country("PA", "PANAMA", "Panama", "PAN", "591"));
			data.add(new Country("PG", "PAPUA NEW GUINEA", "Papua New Guinea", "PNG", "598"));
			data.add(new Country("PY", "PARAGUAY", "Paraguay", "PRY", "600"));
			data.add(new Country("PE", "PERU", "Peru", "PER", "604"));
			data.add(new Country("PH", "PHILIPPINES", "Philippines", "PHL", "608"));
			data.add(new Country("PN", "PITCAIRN", "Pitcairn", "PCN", "612"));
			data.add(new Country("PL", "POLAND", "Poland", "POL", "616"));
			data.add(new Country("PT", "PORTUGAL", "Portugal", "PRT", "620"));
			data.add(new Country("PR", "PUERTO RICO", "Puerto Rico", "PRI", "630"));
			data.add(new Country("QA", "QATAR", "Qatar", "QAT", "634"));
			data.add(new Country("RE", "REUNION", "Reunion", "REU", "638"));
			data.add(new Country("RO", "ROMANIA", "Romania", "ROM", "642"));
			data.add(new Country("RU", "RUSSIAN FEDERATION", "Russian Federation", "RUS", "643"));
			data.add(new Country("RW", "RWANDA", "Rwanda", "RWA", "646"));
			data.add(new Country("SH", "SAINT HELENA", "Saint Helena", "SHN", "654"));
			data.add(new Country("KN", "SAINT KITTS AND NEVIS", "Saint Kitts and Nevis", "KNA", "659"));
			data.add(new Country("LC", "SAINT LUCIA", "Saint Lucia", "LCA", "662"));
			data.add(new Country("PM", "SAINT PIERRE AND MIQUELON", "Saint Pierre and Miquelon", "SPM", "666"));
			data.add(new Country("VC", "SAINT VINCENT AND THE GRENADINES", "Saint Vincent and the Grenadines", "VCT",
					"670"));
			data.add(new Country("WS", "SAMOA", "Samoa", "WSM", "882"));
			data.add(new Country("SM", "SAN MARINO", "San Marino", "SMR", "674"));
			data.add(new Country("ST", "SAO TOME AND PRINCIPE", "Sao Tome and Principe", "STP", "678"));
			data.add(new Country("SA", "SAUDI ARABIA", "Saudi Arabia", "SAU", "682"));
			data.add(new Country("SN", "SENEGAL", "Senegal", "SEN", "686"));
			data.add(new Country("CS", "SERBIA AND MONTENEGRO", "Serbia and Montenegro", null, null));
			data.add(new Country("SC", "SEYCHELLES", "Seychelles", "SYC", "690"));
			data.add(new Country("SL", "SIERRA LEONE", "Sierra Leone", "SLE", "694"));
			data.add(new Country("SG", "SINGAPORE", "Singapore", "SGP", "702"));
			data.add(new Country("SK", "SLOVAKIA", "Slovakia", "SVK", "703"));
			data.add(new Country("SI", "SLOVENIA", "Slovenia", "SVN", "705"));
			data.add(new Country("SB", "SOLOMON ISLANDS", "Solomon Islands", "SLB", "090"));
			data.add(new Country("SO", "SOMALIA", "Somalia", "SOM", "706"));
			data.add(new Country("ZA", "SOUTH AFRICA", "South Africa", "ZAF", "710"));
			data.add(new Country("GS", "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
					"South Georgia and the South Sandwich Islands", null, null));
			data.add(new Country("ES", "SPAIN", "Spain", "ESP", "724"));
			data.add(new Country("LK", "SRI LANKA", "Sri Lanka", "LKA", "144"));
			data.add(new Country("SD", "SUDAN", "Sudan", "SDN", "736"));
			data.add(new Country("SR", "SURINAME", "Suriname", "SUR", "740"));
			data.add(new Country("SJ", "SVALBARD AND JAN MAYEN", "Svalbard and Jan Mayen", "SJM", "744"));
			data.add(new Country("SZ", "SWAZILAND", "Swaziland", "SWZ", "748"));
			data.add(new Country("SE", "SWEDEN", "Sweden", "SWE", "752"));
			data.add(new Country("CH", "SWITZERLAND", "Switzerland", "CHE", "756"));
			data.add(new Country("SY", "SYRIAN ARAB REPUBLIC", "Syrian Arab Republic", "SYR", "760"));
			data.add(new Country("TW", "TAIWAN, PROVINCE OF CHINA", "Taiwan, Province of China", "TWN", "158"));
			data.add(new Country("TJ", "TAJIKISTAN", "Tajikistan", "TJK", "762"));
			data.add(new Country("TZ", "TANZANIA, UNITED REPUBLIC OF", "Tanzania, United Republic of", "TZA", "834"));
			data.add(new Country("TH", "THAILAND", "Thailand", "THA", "764"));
			data.add(new Country("TL", "TIMOR-LESTE", "Timor-Leste", null, null));
			data.add(new Country("TG", "TOGO", "Togo", "TGO", "768"));
			data.add(new Country("TK", "TOKELAU", "Tokelau", "TKL", "772"));
			data.add(new Country("TO", "TONGA", "Tonga", "TON", "776"));
			data.add(new Country("TT", "TRINIDAD AND TOBAGO", "Trinidad and Tobago", "TTO", "780"));
			data.add(new Country("TN", "TUNISIA", "Tunisia", "TUN", "788"));
			data.add(new Country("TR", "TURKEY", "Turkey", "TUR", "792"));
			data.add(new Country("TM", "TURKMENISTAN", "Turkmenistan", "TKM", "795"));
			data.add(new Country("TC", "TURKS AND CAICOS ISLANDS", "Turks and Caicos Islands", "TCA", "796"));
			data.add(new Country("TV", "TUVALU", "Tuvalu", "TUV", "798"));
			data.add(new Country("UG", "UGANDA", "Uganda", "UGA", "800"));
			data.add(new Country("UA", "UKRAINE", "Ukraine", "UKR", "804"));
			data.add(new Country("AE", "UNITED ARAB EMIRATES", "United Arab Emirates", "ARE", "784"));
			data.add(new Country("GB", "UNITED KINGDOM", "United Kingdom", "GBR", "826"));
			data.add(new Country("US", "UNITED STATES", "United States", "USA", "840"));
			data.add(new Country("UM", "UNITED STATES MINOR OUTLYING ISLANDS", "United States Minor Outlying Islands",
					null, null));
			data.add(new Country("UY", "URUGUAY", "Uruguay", "URY", "858"));
			data.add(new Country("UZ", "UZBEKISTAN", "Uzbekistan", "UZB", "860"));
			data.add(new Country("VU", "VANUATU", "Vanuatu", "VUT", "548"));
			data.add(new Country("VE", "VENEZUELA", "Venezuela", "VEN", "862"));
			data.add(new Country("VN", "VIET NAM", "Viet Nam", "VNM", "704"));
			data.add(new Country("VG", "VIRGIN ISLANDS, BRITISH", "Virgin Islands, British", "VGB", "092"));
			data.add(new Country("VI", "VIRGIN ISLANDS, U.S.", "Virgin Islands, U.s.", "VIR", "850"));
			data.add(new Country("WF", "WALLIS AND FUTUNA", "Wallis and Futuna", "WLF", "876"));
			data.add(new Country("EH", "WESTERN SAHARA", "Western Sahara", "ESH", "732"));
			data.add(new Country("YE", "YEMEN", "Yemen", "YEM", "887"));
			data.add(new Country("ZM", "ZAMBIA", "Zambia", "ZMB", "894"));
			data.add(new Country("ZW", "ZIMBABWE", "Zimbabwe", "ZWE", "716"));

		}
	}

}
